# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://www.abrahamchaibi.me/
baseurl: ""
title: Abraham Chaibi
author: Abraham Chaibi
description: Personal Website
avatar: profile.png
email: abrahamchaibi@gmail.com
github: abrahamchaibi
linkedin: abraham-chaibi-b217b13b
disqus: abrahamchaibi-com

# needed for travis-ci build
exclude: [vendor]
